### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by mdsumner** [SymbolixAU/colourvalues#10]
If you pre-cache the palette, then standard scaling/index is not too shabby - but is that cheating? 

If you pre-cache the calculations in a closure, with colorRampPalette you get good performance at a loss of generality (the alpha, begin, direction etc. have to go in at the start, they can't be modified on-the-fly). 

I keep getting varied results, so I'm going to change to a different machine - I'm beating RcppViridis which can't be right ... and it's not always the result I get. 

Here's the code I'm trying. Basically I think it's unfair to use col_numeric, when there's two things going on 1) colour ramp generation 2) indexing of raw values to the ramp

```R
library(microbenchmark)
library(ggplot2)
library(scales)
library(viridisLite)

mkfun <-
  function (alpha = 1, begin = 0, end = 1, direction = 1, option = "D")
  {
    if (begin < 0 | begin > 1 | end < 0 | end > 1) {
      stop("begin and end must be in [0,1]")
    }
    if (abs(direction) != 1) {
      stop("direction must be 1 or -1")
    }
    if (direction == -1) {
      tmp <- begin
      begin <- end
      end <- tmp
    }
    option <- switch(EXPR = option, A = "A", magma = "A", B = "B",
                     inferno = "B", C = "C", plasma = "C", D = "D", viridis = "D",
                     E = "E", cividis = "E", {
                       warning(paste0("Option '", option, "' does not exist. Defaulting to 'viridis'."))
                       "D"
                     })
    map <- viridisLite::viridis.map[viridisLite::viridis.map$opt ==
                                      option, ]
    map_cols <- grDevices::rgb(map$R, map$G, map$B)
    grDevices::colorRampPalette(map_cols, space = "Lab",
                                interpolate = "spline")
  }

## a closure to pre-calc
fn_cols_ <- mkfun()
viridis_ <- function(n) {
  fn_cols_(n)
}


n <- 1e6
df <- data.frame(x = rnorm(n = n))
pal <- viridis::viridis(256)

m <- microbenchmark(
  RcppViridis = { RcppViridis::colour_values(x = df$x) },
  ## closure result, return value from colorRampPalette
  scales_prefun = {viridis_(256)[scales::rescale(df$x, to = c(1, 256))]},
  ## viridis() in its glory
  scales_live = {viridis::viridis(256)[scales::rescale(df$x, to = c(1, 256))]},
   ## cheating with a colour ramp saved already 
  scales_precache = {pal[scales::rescale(df$x, to = c(1, 256))]},
  #scales = { col_numeric(palette = rgb(subset(viridis.map, opt=="D")[, 1:3]), domain = range(df$x))(df$x) },
  times = 250
)
m


x <- data.frame(a = 10, x = 1:256)
x$rcpp <- RcppViridis::colour_values(x$x)
x$prefun <- viridis_(256)[scales::rescale(x$x, to = c(1, 256))]
x$live <- viridis::viridis(256)[scales::rescale(x$x, to = c(1, 256))]
x$precache <- pal[scales::rescale(x$x, to = c(1, 256))]

barplot(height = x$a, col = x$rcpp, border = NA, space = 0)
barplot(height = x$a, col = x$prefun, border = NA, space = 0)
barplot(height = x$a, col = x$live, border = NA, space = 0)
barplot(height = x$a, col = x$precache, border = NA, space = 0)

```

**Comment by SymbolixAU** [comment]
Thanks for these.

```
<IGNORE THIS BENCHMARK, IT WAS WRONG>
```
I think a couple of key considerations are

1. How easy is it for the user
2. Is it 'general' / will it work on-the-fly 
3. Can I link to the library at the C-level without using R as an intermediary.

**Comment by mdsumner** [comment]
All good points!  I'm learning from this, and keen to have easy tools to do all this - I'd avoided the problem thus far in rgl but I need way better colour control. 

What do you mean scales_prefun doesn't run? An error? I'm missing something

**Comment by SymbolixAU** [comment]
> What do you mean scales_prefun doesn't run?

Never mind, there was a carriage-return

```r
mkfun <-
  function (alpha = 1, begin = 0, end = 1, direction = 1, option = "D")
  {
``` 

which I didn't pick up on. Working now.

**Comment by SymbolixAU** [comment]
closing as no longer an 'issue'. I'm happy there are quicker ways using existing packages, but the performance of `colourvalues` is acceptable (to me), and its ease-of-use and interoperability are what I'm after too.
