### ISSUE TITLE
odd behaviour when colouring based on a numeric vector

### ISSUE THREAD

**Issue by tim-salabim** [SymbolixAU/colourvalues#24]
I encountered some rather odd behaviour when using `colur_values_rgb` on a numeric vector. The vector gets modified by reference, see below.

```r
# integer works as expected
set.seed(23)
v = sample.int(100, 10)
v
# [1] 58 23 33 69 79 41 91 94 78 93
clrs = colour_values_rgb(v, include_alpha = FALSE) / 255
v
# [1] 58 23 33 69 79 41 91 94 78 93

# numeric gets mumbled
set.seed(23)
v = as.numeric(sample.int(100, 10))
v
# [1] 58 23 33 69 79 41 91 94 78 93
clrs = colour_values_rgb(v, include_alpha = FALSE) / 255
v
# [1] 0.4929577 0.0000000 0.1408451 0.6478873 0.7887324 0.2535211 0.9577465 1.0000000 0.7746479 0.9859155
```` 
Any ideas?
The colours are identical, btw.

**Comment by SymbolixAU** [comment]
Yes, that's unexpected. The `numeric` `v` is returned scaled [0,1] , so I might need to put a `clone()` in there somewhere. 

But that doesn't explain why the `integer` works though. 

I'll investigate tomorrow

**Comment by SymbolixAU** [comment]
Ok, a bit of digging,

All my `Rcpp` method signatures for "numbers" are `Rcpp::NumericVector`. So, when passing in an integer vector (from R), it has to be coerced to a `NumericVector`, thus a copy is made, and hence the difference between the integer and numeric results. 

References: 
- https://stackoverflow.com/a/38104905/5977215
- https://stackoverflow.com/a/11300707/5977215

Fix is incoming

**Comment by tim-salabim** [comment]
Thanks! Just tested and behaves as expected now.
