### ISSUE TITLE
< 5 values in vector & alpha

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#25]
```r
colourvalues::color_values(1:2, alpha = 1:2)

Error in rcpp_colour_num_value_string_palette_hex(x, palette, na_colour,  : 
  Interpolation using a cubic b spline with derivatives estimated at the endpoints requires at least 5 points.
```

**Comment by SymbolixAU** [comment]
Not actually a bug, but it needed handling. Updated docs and tests to say a vector of alpha values requires at least 5 values.

**Comment by SymbolixAU** [comment]
Maybe this should be handled by making the `alpha` vector at least 5 values by inserting the mean of the vector?

**Comment by MichaelChirico** [comment]
I think that makes sense, as long as it's documented?

**Comment by dcooley** [comment]
yeah so this is documented in `?colourvalues::colour_values`, 

> The palette can either be
> 
> String - use colour_palettes() to view available palettes
> 
> Matrix - At least 5 rows, and 3 (or 4) columns representing the red, green and blue (and alpha) values

and there's a [`palette_check()`](https://github.com/SymbolixAU/colourvalues/blob/master/R/colourvalues-package.R#L10) to check the number of rows of a matrix. 

So I think it's fine over here, but the docs and error handling should be propagated into mapdeck

**Comment by dcooley** [comment]
added a check in .hpp file for [matrix rows](https://github.com/SymbolixAU/colourvalues/commit/377e30a9bb2868c3c6f0b3ed78938882f5fd0cfe)
