### ISSUE TITLE
alpha

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#4]
support alpha

---
## TODO
- [x] accept alpha
- [x] alpha scaled according to a variable (e.g. a numeric column of a data.frame)
- [x] return alpha

**Comment by tim-salabim** [comment]
What about a `na.alpha` to e.g. set all NAs as transparent?

**Comment by SymbolixAU** [comment]
setting `alpha = 0` should do this

```r
df <- data.frame(a = 10, x = 1:260)
df$col <- colour_values(df$x, alpha = 0)
barplot(height = df$a, col = df$col, border = NA, space = 0)


df <- data.frame(a = 10, x = 1:260)
df$col <- colour_values(df$x, alpha = 15)
barplot(height = df$a, col = df$col, border = NA, space = 0)
```

**Comment by SymbolixAU** [comment]
<sorry - misread your request>

yes - good idea.

**Comment by SymbolixAU** [comment]
@tim-salabim can I get your thoughts on this scenario:

Given this function call

```r
colour_values(1:5, alpha = 1:5)
```
should the `alpha` values be 

1. left as-is `1:5` (which, when converted to RRGGBBAA will be in the region of `"00"`), or
2. assumed to be a variable which needs to be scaled to `1:5 / 5 * 255`  (so when converted will be `"00","3F","7F","BF","FF"` ?

**Comment by tim-salabim** [comment]
I'd say 2. If you're scaling the values you should also scale the alpha vector.
But I'd also say alpha should be within [0,1]. 

Also, would someone actually want to specify a vector of alpha? The most common scenarios in my opinion are:

1. a constant alpha over all values
2. a special alpha for special values (i.e. NAs)
3. mapping of alpha to a (second) variable (in which case the UI usually accepts the name of a df column).

For 3. it should then be scaled to the same as the values vector.

**Comment by SymbolixAU** [comment]
I'm inclined to agree, and I think this point is key
> mapping of alpha to a (second) variable (in which case the UI usually accepts the name of a df column).

With regards to
> But I'd also say alpha should be within [0,1].

If we're scaling a column/vector of data then I don't think it matters the range of the values, as they have to be in [0,255] to be converted to `#RRGGBBAA`

**Comment by tim-salabim** [comment]
> If we're scaling a column/vector of data then I don't think it matters the range of the values, as they have to be in [0,255] to be converted to #RRGGBBAA

Agreed!

**Comment by SymbolixAU** [comment]
`na.alpha` as `0` or `255` by default?

**Comment by SymbolixAU** [comment]
although, it can be specified through `na_colour`

```r
colour_values(c(1,2,NA,4,5), na_colour = "#80808000")
colour_values(c(1,2,NA,4,5), na_colour = "#808080FF")
colour_values(c(1,2,NA,4,5), na_colour = "#80808080")
```

**Comment by tim-salabim** [comment]
I'd use the same default as `alpha`

**Comment by SymbolixAU** [comment]
Do you think a separate `na.alpha` is needed given it can be specified in `na_colour` ?

**Comment by tim-salabim** [comment]
It depends, for leaflet e.g. the 8-digit hex notation was not respected (i.e. nothing was shown if in 8-digit hex) in some cases with the earlier (pre leafletjs 1.x). I am not sure how well 8-digit hex is supported in general (i.e. beyond web).

My approach in such cases is usually to not overload the api but wait and see if there is a need, so I would not implement it for now and highlight how to set it via `na_colour`. 

Sorry for causing the stir and then recommend to not implement it... I had forgotten why we implemented a specific `na.alpha` in mapview.

**Comment by SymbolixAU** [comment]
It's not a problem; these discussions are important 👍
