### ISSUE TITLE
get_palette() - return hex

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#58]
from [here](https://github.com/ATFutures/upthat/pull/27#issue-345184995)

have an argument in `get_palette()` which returns the colours as hex, rather than rgb.

**Comment by mpadge** [comment]
That would just make things one step easier, because it's the only (simple) way to both diagnose a problem and find a solution from the same help file. Would help lots, I'd say

**Comment by SymbolixAU** [comment]
done

```r
get_palette("viridis", rgb = FALSE )
  [1] "#440154" "#440255" "#440357" "#450558" ...
```

**Comment by mpadge** [comment]
brilliant - thanks loads!
