### ISSUE TITLE
reverse palette

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#6]
reverse palette

**Comment by SymbolixAU** [comment]
Given you can pass in a palette, I'm going to leave this for the user.

```r
pal <- viridis()
pal <- pal[nrow(pal):1, ]
rev(colour_values(1:20)) == colour_values(1:20, palette = as.matrix(pal * 255) )
```

**Comment by SymbolixAU** [comment]
Reopening - would be good to reverse one of the in-built palettes

**Comment by dcooley** [comment]
I can't think of an easy way to implement this without passing another function to src. 

Probably the best way is to have a function which returns any of the available palettes, then the user can simply reverse it.

**Comment by dcooley** [comment]
I've exposed the palettes through 

```
get_palette( "viridis" )
```

so now the user can revers this.
