### ISSUE TITLE
remove Boost

### ISSUE THREAD

**Issue by dcooley** [SymbolixAU/colourvalues#63]
as per https://github.com/SymbolixAU/jsonify/issues/65

---

TODO

- [x] dates
- [ ] cubic b spline

**Comment by SymbolixAU** [comment]
for interpolators, I'm delaying this until after 20200320, as I need to get a new version of `colourvalues` on CRAN so `spatialwidget` can get on CRAN.

So I have made a local copy of the BH math folders, and removed dependency on BH

**Comment by dcooley** [comment]
replacing cubic-b-spline may not be easy and / or feasible. The Boost implementation is good and stable. There is a posilbility in [ttk592](https://github.com/ttk592/spline/), but it gives slightly different results, and may differ at the ends of the spline
