### ISSUE TITLE
include_alpha = FALSE still returns alpha for NA values

### ISSUE THREAD

**Issue by chrislim5** [SymbolixAU/colourvalues#69]
Option include_alpha = FALSE still returns hex string with alpha value for NA values

`colourvalues::color_values(c(0, 1, NA), include_alpha = FALSE, na_colour = "808080")`
Returns `[1] "#440154"  "#FDE725"  "808080FF"`

**Comment by dcooley** [comment]
Thanks for reporting; I'll take a look.

---

Also note youre `na_colour` isn't a valid hex-string, it needs a `#` at the start

**Comment by chrislim5** [comment]
Ah, missed that. Thanks.

**Comment by dcooley** [comment]
ok, please try the latest version

```r
remotes::install_github("SymbolixAU/colourvalues")

colourvalues::color_values(c(0, 1, NA), include_alpha = FALSE, na_colour = "#808080")
[1] "#440154" "#FDE725" "#808080"

colourvalues::color_values(c(0, 1, NA), include_alpha = FALSE, na_colour = "#808080FF")
[1] "#440154" "#FDE725" "#808080"
```

**Comment by chrislim5** [comment]
Fixed - thanks for the quick response!
