### ISSUE TITLE
package discussion

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/colourvalues#8]
I'm using this issue to keep track of thoughts and ideas in the early stages of this package. 

#### Non-viridis palettes
- user-supplied, or built-in wth the package

#### Package name
- I'm not completely convinced on `RcppViridis`
- if we include other palettes this will have to change too.

**Comment by tim-salabim** [comment]
Regarding factor/charatcer types, I think it would be nice to have unordered palette(s) as well, e.g. the `Set*` palettes from colorbrewer2.org. A few diverging ones would also be great... then we would have all the palettes we need for (fast) map making.

**Comment by SymbolixAU** [comment]
I'm keen on allowing the user to supply palettes, either as hex-colours, or rgb matrices. I'm undecided about offering them by default though.

**Comment by tim-salabim** [comment]
Agreed, if the user can supply palettes, no need to have them in the package IMO

**Comment by barryrowlingson** [comment]
Thoughts: I'd call the function `colour_values` rather than `colour_variables`. Also you'll find certain people think "colour" doesn't have a "u" in it. Also I'd say you were mapping values to colours, since (mathematically) a mapping is an operation from a domain (the values) to a range (the colours).

**Comment by SymbolixAU** [comment]
I'll provide a `color_variables <- colour_variables` option too 

Interesting point re values vs variables. I'm using "variables" as the collective term for all the values. Would `colour_values <- colour_variables` be overkill?

**Comment by SymbolixAU** [comment]
I've currently implemented a `return` argument to specify how the data is returned, either as a hex string or RGB matrix

```r
> colour_values(1:5)
[1] "#440154FF" "#3B528BFF" "#21908CFF" "#5DC963FF" "#FDE725FF"

> colour_values(1:5, return = "rgb")
     [,1] [,2] [,3] [,4]
[1,]   68    1   84  255
[2,]   59   82  139  255
[3,]   33  144  140  255
[4,]   93  201   99  255
[5,]  253  231   37  255
```

Should I in stead have two different functions, `colour_hex()` and `colour_rgb()`?

**Comment by SymbolixAU** [comment]
Think I'm going with 

- `colour_values()`        - returning hex strings
- `colour_values_rgb()` - returning RGB(A) matrix

**Comment by SymbolixAU** [comment]
@tim-salabim if I released this package now would it be useable for you? The only thing I don't think I'm natively supporting is allowing the user to supply a [range of colours](https://github.com/SymbolixAU/RcppViridis/issues/1). But this can be handled by each application by providing the `palette` they want to use.

**Comment by SymbolixAU** [comment]
Is the package name `RcppViridis` too 'restrictive' in getting across what this package does? Some other options which have been floating around

- colourvalues <-- I'm starting to prefer this one
- colourfast
- colourme

**Comment by tim-salabim** [comment]
I will have a look later today or tomorrow. I, too find RcppViridis not ideal.

**Comment by SymbolixAU** [comment]
[renamed](https://github.com/SymbolixAU/colourvalues/commit/395cca821f40bd5261c360083d7da45675572970) to `colourvalues`

**Comment by tim-salabim** [comment]
@SymbolixAU sorry, I got sidetracked with mapview update to avoid it being taken off CRAN. I will test asap

**Comment by tim-salabim** [comment]
@SymbolixAU I am confident that the package is usable in mapview as is. It may take me a while to implement everything but I think all I need is there. Thanks for putting this together. I'm really impressed with the speed! 
Great work! As always!

**Comment by SymbolixAU** [comment]
Thanks for taking the time to test & review. It's really helpful.
